name: boom_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Map
  flutter_map: ^8.1.0
  latlong2: ^0.9.0
  #flutter_map_marker_cluster:
  #  git:
  #    url: https://github.com/rorystephenson/flutter_map_marker_cluster.git
  #    ref: v1.4.1
  #flutter_map_marker_cluster: ^1.3.1  # Version compatible avec flutter_map v6
  flutter_map_location_marker: ^10.1.0
  flutter_map_line_editor: ^8.0.0
  flutter_map_marker_cluster_plus: ^1.4.1
  riverpod_annotation: ^1.0.6
  geolocator: ^14.0.2
  flutter_bloc: ^8.1.2

  # Network
  http: ^1.1.0

  # State management
  provider: ^6.1.5

  # Storage
  sqflite: ^2.3.0
  path_provider: ^2.0.12

  # Permissions
  permission_handler: ^11.3.1
  image_picker: ^1.0.4
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/unused/