const Map<String, String> okIcons = {
  "Abattage": "assets/icons/abattage.png",
  "Avatar": "assets/icons/avatar.png",
  "Add Folder": "assets/icons/add-folder.png",
  "Export PDF": "assets/icons/export_pdf.png",
  "Export Database": "assets/icons/export_database.png",
  "Edit": "assets/icons/edit.png",
  "Export Data": "assets/icons/export_data.png",
  "Filter": "assets/icons/filter.png",
  "Layer": "assets/icons/layer.png",
  "Clock 512w": "assets/icons/li_clock_512w.png",
  "Home 01": "assets/icons/li_home_01.png",
  "Pie Chart 01": "assets/icons/li_pie-chart_01.png",
  "Location": "assets/icons/location.png",
  "Switch": "assets/icons/switch.png",
  "Position": "assets/icons/position.png",
  "Lock Screen": "assets/icons/lock_screen.png",
  "Save": "assets/icons/save_icon.png",
  'Copy': 'assets/icons/copy.png',
  "Delete draw": "assets/icons/delete_draw.png",
  "Edit draw": "assets/icons/edit_draw.png",
  "Draw polygon": "assets/icons/draw_polygon.png",
  "Draw line": "assets/icons/draw_line.png",
  "Draw point": "assets/icons/draw_point.png",
};
